import { type PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Good Place",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className="dark">
      <body className={cn(inter.className, "flex min-h-screen flex-col")}>
        <Navbar />
        <main className="flex flex-1 flex-col text-center">{children}</main>
      </body>
    </html>
  );
}
